# Generated by Django 5.1 on 2024-09-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField()),
                ('pickup_at', models.TimeField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('fare', models.DecimalField(blank=True, decimal_places=2, default=30, max_digits=10, null=True)),
                ('ride_status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('confirmed', 'confirmed'), ('assigned', 'assigned'), ('cancelled', 'cancelled'), ('Started', 'Started'), ('completed', 'completed')], default=('pending', 'pending'), max_length=20)),
                ('Front_pic', models.ImageField(blank=True, default=None, null=True, upload_to='ride_images')),
                ('Back_pic', models.ImageField(blank=True, default=None, null=True, upload_to='ride_images')),
                ('selfie', models.ImageField(blank=True, default=None, null=True, upload_to='ride_images')),
                ('opening_kms_screen', models.ImageField(blank=True, default=None, null=True, upload_to='ride_images')),
                ('closing_kms_screen', models.ImageField(blank=True, default=None, null=True, upload_to='ride_images')),
                ('opening_kms_input', models.IntegerField(blank=True, null=True)),
                ('closing_kms_input', models.IntegerField(blank=True, null=True)),
                ('toll_fare', models.IntegerField(blank=True, null=True)),
                ('parking_fare', models.IntegerField(blank=True, null=True)),
                ('is_extra', models.BooleanField(default=False)),
                ('payment_status', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
