# Generated by Django 4.2.14 on 2024-09-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='payment_type',
            field=models.CharField(choices=[('online', 'online'), ('cash', 'cash'), ('wallet', 'wallet')], default='cash', max_length=20),
            preserve_default=False,
        ),
    ]
