# Generated by Django 4.2.14 on 2024-09-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0003_ride_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='rideSlug',
            field=models.SlugField(default='ride_info', max_length=100, null=True),
        ),
    ]
