# Generated by Django 4.2.14 on 2024-09-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0004_ride_rideslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='rideSlug',
            field=models.SlugField(blank=True, default='ride_info', max_length=100, null=True),
        ),
    ]
