# Generated by Django 4.2.14 on 2024-10-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0006_alter_ride_rideslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Received', 'Received')], default=('Pending', 'Pending'), max_length=20, null=True),
        ),
    ]
